---
- name: Collects the id of the current user
  hosts: testserver
  tasks:
    - name: Capture output of id command
      command: id -un
      register: login
    - debug: msg="Logged in as user {{ login.stdout }}"