---
- name: Copy user key to host
  gather_facts: no
  hosts: all
  vars:
    pubkey: "{{ '~' | expanduser }}/.ssh/id_rsa.pub"

  tasks:
    - authorized_key: user={{ ansible_ssh_user }} key="{{ lookup('file', pubkey) }}"
